version: '3.2'

services:
  nc:
    image: nextcloud:28-fpm-alpine
    container_name: nextcloud-fpm
    hostname: nextcloud-fpm
    restart: always
    volumes:
      - nc_data:/var/www/html
    networks:
      - redisnet
      - dbnet
      - webnet
    environment:
      - REDIS_HOST=nextcloud-redis
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
    depends_on:
      - redis
      - db
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
      - nextcloud_admin_user
      - nextcloud_admin_password

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    expose:
      - 6379
    networks:
      - redisnet

  db:
    image: postgres:15-alpine
    container_name: nextcloud-db
    restart: always
    expose:
      - 5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - dbnet
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  web:
    image: nginx:1.25-alpine
    container_name: nextcloud-web
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - nc_data:/var/www/html:ro
    networks:
      - webnet
    depends_on:
      - nc

volumes:
  db_data:
  nc_data:

networks:
  dbnet:
  redisnet:
  webnet:

secrets:
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
